version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgresql-container
    environment:
      POSTGRES_USER: toyland
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: toyland
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  springboot-app:
    image: 536697233833.dkr.ecr.ap-northeast-2.amazonaws.com/project/toyland:latest
    container_name: springboot-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql-container:5432/toyland
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      OPENAI_API_URL: ${OPENAI_API_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    env_file:
      - .env

volumes:
  postgres_data: