###Qna 생성
POST http://localhost:8080/api/v1/qna
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzM5OTM4OTY1LCJpYXQiOjE3Mzk5MzUzNjV9.16QOXsLipbGTtxCMH_KLb90JjaW0l-ZqUNn3c49Ttgs

{
  "question": "if i say korean, then speak korean.",
  "storeId": "2e11ee82-82a9-41cc-ac52-3b532887d5e6"
}

###Qna 전체 조회
GET http://localhost:8080/api/v1/qna/search?page=0&size=10&sort=created_at,asc&
    storeId=2e11ee82-82a9-41cc-ac52-3b532887d5e6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzM5OTM4OTY1LCJpYXQiOjE3Mzk5MzUzNjV9.16QOXsLipbGTtxCMH_KLb90JjaW0l-ZqUNn3c49Ttgs

###Qna 단건 조회
GET http://localhost:8080/api/v1/qna/qnaId=5e38653c-cff0-4b16-9f25-e99e3ea6f506
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzM5ODk1NzQ1LCJpYXQiOjE3Mzk4OTIxNDV9.tHY-uCjl9EMUSf7KpVgB45uwovcqLSF19dYH80aLZk4

###Qna 수정
PUT http://localhost:8080/api/v1/qna/29e38b2b-e66d-4ccd-aa82-32799fdc17ea
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzM5ODk1NzQ1LCJpYXQiOjE3Mzk4OTIxNDV9.tHY-uCjl9EMUSf7KpVgB45uwovcqLSF19dYH80aLZk4

{
  "question": "I'm changed",
  "answer": "me too"
}

###Qna 삭제
DELETE http://localhost:8080/api/v1/qna/1727718c-3276-488d-bf43-5e2a0676cdf2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzM5OTMwNjc3LCJpYXQiOjE3Mzk5MjcwNzd9.NTwdcwVM9rvCohRRCJPd35Hun6R654rwAQGY9UAsh9k
