### 주문 생성
POST http://localhost:8080/api/v1/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMDE3NzEzLCJpYXQiOjE3NDAwMTQxMTN9.WycI2pW5Lh7cAqOL97UYntFeXiADhv1GqsD1bXVQ4eU

{
  "orderProducts": [
    {
      "productId": "26c7366c-2560-48a6-93fd-37aa8c19e0f3",
      "price": 10000.00,
      "quantity": 1
    },
    {
      "productId": "13c0a47a-3d34-4dfe-bf0b-babb6e12af82",
      "price": 10000.00,
      "quantity": 2
    }
  ],
  "orderType": "DELIVERY",
  "paymentType": "CARD"
}



### 주문 단 건 조회
GET http://localhost:8080/api/v1/orders/d457aff9-f6de-4033-8c2d-f267eafe45a5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjdXN0b21lciIsImF1dGgiOiJDVVNUT01FUiIsImV4cCI6MTczOTk3OTkzNywiaWF0IjoxNzM5OTc2MzM3fQ.5B-nvNlBJFNDCBN3yr1hH83mQuVQFCyi5zI-TLdBbak



### 주문 삭제
DELETE http://localhost:8080/api/v1/orders/a8615669-a074-4e84-a390-cbcc7902d15a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzM5OTQ4Njk5LCJpYXQiOjE3Mzk5NDUwOTl9.6M_7GYd8GXRTjBc9HNhLqHNk7QucICIXgyrU3hMHAkg

