### 주문 생성
POST http://localhost:8080/api/v1/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzM5OTQ4Njk5LCJpYXQiOjE3Mzk5NDUwOTl9.6M_7GYd8GXRTjBc9HNhLqHNk7QucICIXgyrU3hMHAkg

{
  "orderProducts": [
    {
      "productId": "303a3572-67eb-4ce1-9df6-ca5e38a5082e",
      "price": 10000.00,
      "quantity": 1
    },
    {
      "productId": "0f9a2a88-4522-427e-8bef-13ac1e44307f",
      "price": 20000.00,
      "quantity": 2
    }
  ],
  "orderType": "DELIVERY",
  "paymentType": "CARD"
}


### 주문 삭제
DELETE http://localhost:8080/api/v1/orders/a8615669-a074-4e84-a390-cbcc7902d15a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzM5OTQ4Njk5LCJpYXQiOjE3Mzk5NDUwOTl9.6M_7GYd8GXRTjBc9HNhLqHNk7QucICIXgyrU3hMHAkg

