### 주문 생성
POST http://localhost:8080/api/v1/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjdXN0b21lciIsImF1dGgiOiJDVVNUT01FUiIsImV4cCI6MTc0MDI0OTM0NywiaWF0IjoxNzQwMjQ1NzQ3fQ.jobsXSnPX2nxOaUsyLoksXk-7llcRckA9mkWFlJU5PA

{
  "orderProducts": [
    {
      "productId": "e20e9465-3c4f-401a-bffc-bb6a3d73cf36",
      "price": 500.00,
      "quantity": 3
    },
    {
      "productId": "ae65de91-c503-4188-a4e9-06eb827bf37c",
      "price": 500.00,
      "quantity": 3
    }
  ],
  "orderType": "ONLINE_DELIVERY",
  "paymentType": "CARD",
  "addressId": "4a16ce7b-628a-436b-a9dd-fcf220f06c3d",
  "addressDetail": "200동, 2000호",
  "orderRequest": "맵게 해주세요."
}



### 주문 단 건 조회
GET http://localhost:8080/api/v1/orders/d457aff9-f6de-4033-8c2d-f267eafe45a5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjdXN0b21lciIsImF1dGgiOiJDVVNUT01FUiIsImV4cCI6MTczOTk3OTkzNywiaWF0IjoxNzM5OTc2MzM3fQ.5B-nvNlBJFNDCBN3yr1hH83mQuVQFCyi5zI-TLdBbak



### 주문 수정(주문 변경)
PUT http://localhost:8080/api/v1/orders/b7745ace-f7c5-4eeb-a84f-203d533d21c0/menu
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjdXN0b21lciIsImF1dGgiOiJDVVNUT01FUiIsImV4cCI6MTc0MDM3MzM4NiwiaWF0IjoxNzQwMzY5Nzg2fQ.epH77ajxJ_4aFOPshIME_uI_UGz4rcxqWRbKyG3VRro


{
  "orderProducts": [
    {
      "productId": "e20e9465-3c4f-401a-bffc-bb6a3d73cf36",
      "price": 3333.00,
      "quantity": 555
    },
    {
      "productId": "ae65de91-c503-4188-a4e9-06eb827bf37c",
      "price": 3333.00,
      "quantity": 555
    }
  ],
  "orderType": "ONLINE_DELIVERY",
  "paymentType": "CASH",
  "addressId": "4a16ce7b-628a-436b-a9dd-fcf220f06c3d",
  "addressDetail": "300동, 3000호",
  "orderRequest": "그냥 안맵게 해주세요."
}


### 주문 수정(주문 취소)
PUT http://localhost:8080/api/v1/orders/b7745ace-f7c5-4eeb-a84f-203d533d21c0/status?status=ORDER_CANCELED
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvd25lciIsImF1dGgiOiJPV05FUiIsImV4cCI6MTc0MDM3MzQ3NiwiaWF0IjoxNzQwMzY5ODc2fQ.eC0Ux31DJdlqpP1m3cJAzxtZnw0z7jn1VgYyyy7m7lI



### 주문 수정(주문 접수)
PUT http://localhost:8080/api/v1/orders/b7745ace-f7c5-4eeb-a84f-203d533d21c0/status?status=ORDER_COMPLETED
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvd25lciIsImF1dGgiOiJPV05FUiIsImV4cCI6MTc0MDM3MzUzNiwiaWF0IjoxNzQwMzY5OTM2fQ.a61vupZxPPDOr49UmE7BJIvYgDvYhHMRa-nZC5lFs7s



### 주문 삭제
DELETE http://localhost:8080/api/v1/orders/a8615669-a074-4e84-a390-cbcc7902d15a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzM5OTQ4Njk5LCJpYXQiOjE3Mzk5NDUwOTl9.6M_7GYd8GXRTjBc9HNhLqHNk7QucICIXgyrU3hMHAkg






### 주문 검색 (고객이 자신의 주문 목록 검색)
GET http://localhost:8080/api/v1/orders/search?orderStatus=ORDER_COMPLETED&page=0&size=10&sort=createdAt,asc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjdXN0b21lciIsImF1dGgiOiJDVVNUT01FUiIsImV4cCI6MTc0MDMwMDg2MiwiaWF0IjoxNzQwMjk3MjYyfQ.IM7s9tkdOpTEPNmcRjJE2DUd0JE6W3NKeb_AG4snTqw




### 주문 검색 (음식점 주인이 자신의 음식점 주문 목록 검색)
GET http://localhost:8080/api/v1/orders/search?storeId=a9131f3c-53e4-4253-932b-6dc8a897f946&page=0&size=10&sort=createdAt,asc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvd25lciIsImF1dGgiOiJPV05FUiIsImV4cCI6MTc0MDI5OTkyNSwiaWF0IjoxNzQwMjk2MzI1fQ.p9v9xd6uTob3DQu-zqru1UBKLQVfya_S0MTpVm5lBwQ



### 주문 검색 (매니저, 마스터가 모든 주문 목록 검색)
GET http://localhost:8080/api/v1/orders/search?page=0&size=10&sort=createdAt,asc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMzgwMTE2LCJpYXQiOjE3NDAzNzY1MTZ9.eEMbj403wuNTTCAGDiEaFBl2cN7j6ppJKnLGXbSroE8



### 주문 검색 (매니저, 마스터가 주문 상태가 (대기/완료/취소)된 주문 목록 검색)
GET http://localhost:8080/api/v1/orders/search?orderStatus=ORDER_PENDING&page=0&size=10&sort=createdAt,asc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvd25lciIsImF1dGgiOiJPV05FUiIsImV4cCI6MTc0MDI5NjMwMCwiaWF0IjoxNzQwMjkyNzAwfQ.uBUg9n2jOtPeZOUZanBNVHGuye2kBqoua2tFYyJ2rj8



### 주문 검색 (매니저, 마스터가 특정 회원의 주문 목록 검색)
GET http://localhost:8080/api/v1/orders/search?userId=4&page=0&size=10&sort=updatedAt,asc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMjk1ODExLCJpYXQiOjE3NDAyOTIyMTF9.GjByE5Nl-W-efx_4B2UMRpHrOVNtjMORaGD4YmAtdTI



### 주문 검색 (매니저, 마스터가 특정 음식점의 특정 회원 주문 목록 검색)
GET http://localhost:8080/api/v1/orders/search?userId=15&storeId=d3220318-b2f7-46e0-97d0-8bb8d11fd975&page=0&size=10&sort=createdAt,asc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMjk1ODExLCJpYXQiOjE3NDAyOTIyMTF9.GjByE5Nl-W-efx_4B2UMRpHrOVNtjMORaGD4YmAtdTI
