### 결제 생성
POST {{baseUrl}}/api/v1/payments
Content-Type: application/json
Authorization: {{access_token}}

{
  "orderId": "ae8de6e2-8f5e-4172-8df3-c9829521710f",
  "totalPrice": "1000.00"
}


### 결제 단 건 조회
GET {{baseUrl}}/api/v1/payments/cf0f235d-b2ee-4e0d-8ef6-5ab3bb061948
Content-Type: application/json
Authorization: {{access_token}}



### 결제 수정
PUT {{baseUrl}}/api/v1/payments/cf0f235d-b2ee-4e0d-8ef6-5ab3bb061948
Content-Type: application/json
Authorization: {{access_token}}

{
  "id": "cf0f235d-b2ee-4e0d-8ef6-5ab3bb061948",
  "paymentStatus": "COMPLETED",
  "orderId": "ae8de6e2-8f5e-4172-8df3-c9829521710f"
}


### 결제 삭제
DELETE {{baseUrl}}/api/v1/payments/cf0f235d-b2ee-4e0d-8ef6-5ab3bb061948
Content-Type: application/json
Authorization: {{access_token}}



### 결제 검색 (결제상태)
GET {{baseUrl}}/api/v1/payments/search?paymentStatus=COMPLETED&size=5&sort=createdAt,asc
Content-Type: application/json
Authorization: {{access_token}}



### 결제 검색 (결제번호, 결제상태)
GET {{baseUrl}}/api/v1/payments/search?paymentId=0a792c67-1ef6-4421-847f-fd6ea22ca90b&
    paymentStatus=COMPLETED&size=5&sort=createdAt,asc
Content-Type: application/json
Authorization: {{access_token}}
