### 결제 생성
POST http://localhost:8080/api/v1/payments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMDE3NzEzLCJpYXQiOjE3NDAwMTQxMTN9.WycI2pW5Lh7cAqOL97UYntFeXiADhv1GqsD1bXVQ4eU

{
  "orderId": "ae8de6e2-8f5e-4172-8df3-c9829521710f",
  "totalPrice": "1000.00"
}


### 결제 단 건 조회
GET http://localhost:8080/api/v1/payments/cf0f235d-b2ee-4e0d-8ef6-5ab3bb061948
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMDczOTc2LCJpYXQiOjE3NDAwNzAzNzZ9.9oHGITnlt9eXSdX_f66p_MTADbl7ur96Hpko5ZqmXPU



### 결제 수정
PUT http://localhost:8080/api/v1/payments/cf0f235d-b2ee-4e0d-8ef6-5ab3bb061948
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMDc4NzkxLCJpYXQiOjE3NDAwNzUxOTF9.jCSgd6Nd4eMNOKn6hPXneP2m70zOzO8Xbm4yRKekO8U

{
  "id": "cf0f235d-b2ee-4e0d-8ef6-5ab3bb061948",
  "paymentStatus": "COMPLETED",
  "orderId": "ae8de6e2-8f5e-4172-8df3-c9829521710f"
}


### 결제 삭제
DELETE http://localhost:8080/api/v1/payments/cf0f235d-b2ee-4e0d-8ef6-5ab3bb061948
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMDc4NzkxLCJpYXQiOjE3NDAwNzUxOTF9.jCSgd6Nd4eMNOKn6hPXneP2m70zOzO8Xbm4yRKekO8U
