### 상품 생성
POST {{baseUrl}}/api/v1/products
Content-Type: application/json
Authorization: {{access_token}}


{
  "name": "상점2-상품05",
  "price": 50000,
  "isDisplay": false,
  "storeId": "ada1666b-ef33-45bc-8656-0d0b3c3526dc"
}

### 상품 단건 조회
GET {{baseUrl}}/api/v1/products/11dbe8aa-fb36-466b-b404-65207afab640
Authorization: {{access_token}}

### 상품 검색
GET {{baseUrl}}/api/v1/products/search
    ?searchText=가
    &sort=name,desc,created_at
    &size=10
    &page=1
    &storeId=d2a88144-242d-4a87-b607-4846a66d89de
    &isDisplay=false
Authorization: {{access_token}}


### 상품 수정
PUT {{baseUrl}}/api/v1/products/11dbe8aa-fb36-466b-b404-65207afab640
Content-Type: application/json
Authorization: {{access_token}}

{
  "name": "고바",
  "price": 25000,
  "isDisplay": true
}

### 상품 삭제
DELETE {{baseUrl}}/api/v1/products/11dbe8aa-fb36-466b-b404-65207afab640
Content-Type: application/json
Authorization: {{access_token}}