### 상품 생성
POST http://localhost:8080/api/v1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJNQVNURVIiLCJleHAiOjE3Mzk3MjY3NjUsImlhdCI6MTczOTcyMzE2NX0.3jFPg6vcGzkp4U-l0JnCZt9Qnx8N1qBxG0VB0kjC39Q

{
  "name": "고추바사삭",
  "price": 10000,
  "isDisplay": false,
  "storeId": "4a242e8e-7682-4d32-931c-0b43dbf4eb0f"
}