### 지역 생성
POST {{baseUrl}}/api/v1/regions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMTMyOTE0LCJpYXQiOjE3NDAxMjkzMTR9.Y-8F8ElzKmnNuZw8PCZveU_v7cLcbghCv7DS3JFtMUg

{
  "regionName": "서울시12345"
}

### 지역 단 건 조회
GET {{baseUrl}}/api/v1/regions/2bc3ec54-ba61-4e13-96d8-4dc423f3c48d
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMTMyOTE0LCJpYXQiOjE3NDAxMjkzMTR9.Y-8F8ElzKmnNuZw8PCZveU_v7cLcbghCv7DS3JFtMUg


### 지역 수정
PUT {{baseUrl}}/api/v1/regions/2bc3ec54-ba61-4e13-96d8-4dc423f3c48d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMTMyOTE0LCJpYXQiOjE3NDAxMjkzMTR9.Y-8F8ElzKmnNuZw8PCZveU_v7cLcbghCv7DS3JFtMUg

{
  "regionName": "부산시"
}

### 지역 삭제
DELETE {{baseUrl}}/api/v1/regions/2bc3ec54-ba61-4e13-96d8-4dc423f3c48d
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMTMyOTE0LCJpYXQiOjE3NDAxMjkzMTR9.Y-8F8ElzKmnNuZw8PCZveU_v7cLcbghCv7DS3JFtMUg


### 지역 검색(동적 쿼리) //page=0&size=10&sort=createdAt,asc
GET {{baseUrl}}/api/v1/regions/search?regionName=서울시&page=1&size=5&sort=createdAt,asc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMTMyOTE0LCJpYXQiOjE3NDAxMjkzMTR9.Y-8F8ElzKmnNuZw8PCZveU_v7cLcbghCv7DS3JFtMUg
