###review 생성 403 뜨신다고 하심 확인해보기.
POST {{baseUrl}}/api/v1/reviews
Content-Type: application/json
Authorization: {{access_token}}

{
  "orderId": "{{orderId}}",
  "storeId": "{{storeId}}",
  "reviewContent": "쏘쏘",
  "rating": 3
}
> {%
  client.global.set("reviewId", response.headers.valueOf("reviewId"))
%}

###review 한 건 조회
GET {{baseUrl}}/api/v1/reviews/{{reviewId}}
Content-Type: application/json
Authorization: {{access_token}}

###review 페이징 조회
GET {{baseUrl}}/api/v1/reviews/search?page=0&size=10&sort=createdAt,asc&
    storeId={{storeId}}
Content-Type: application/json
Authorization: {{access_token}}

###review 수정
PUT {{baseUrl}}/api/v1/reviews/{{reviewId}}
Content-Type: application/json
Authorization: {{access_token}}

{
  "reviewContent": "좋습니다  변경",
  "rating": 5
}

###review 삭제
DELETE {{baseUrl}}/api/v1/reviews/{{reviewId}}
Content-Type: application/json
Authorization: {{access_token}}

###review 평점조회
GET {{baseUrl}}/api/v1/reviews/avgRate
Content-Type: application/json
Authorization: {{access_token}}

{
  "storeId": "{{storeId}}"
}