### 음식점 생성
POST http://localhost:8080/api/v1/stores
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwNTM3ODg3LCJpYXQiOjE3Mzk5MzMwODd9.E-PWUfNVkpvyNRr--JPLlrdciiTihSdhksmgoehWvE0

{
  "name": "상점3",
  "content": "상점3입니다.",
  "address": "경기도 성남시 분당구 가로 1",
  "regionId": "376ddba6-d9ab-4953-aee6-614e1dfeef7e",
  "ownerId": "2"
}

### 음식점 조회
GET http://localhost:8080/api/v1/stores/8aa9b4ba-83ae-40c6-9984-760f2c5cbf26
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwNTM3ODg3LCJpYXQiOjE3Mzk5MzMwODd9.E-PWUfNVkpvyNRr--JPLlrdciiTihSdhksmgoehWvE0

### 음식점 검색
GET http://localhost:8080/api/v1/stores/search
    ?searchText=상점
    &sort=name,desc,created_at
    &size=10
    &page=1
    &regionId=376ddba6-d9ab-4953-aee6-614e1dfeef7e
    &ownerId=2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwNTM3ODg3LCJpYXQiOjE3Mzk5MzMwODd9.E-PWUfNVkpvyNRr--JPLlrdciiTihSdhksmgoehWvE0


### 음식점 수정
PUT http://localhost:8080/api/v1/stores/8aa9b4ba-83ae-40c6-9984-760f2c5cbf26
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwNTM3ODg3LCJpYXQiOjE3Mzk5MzMwODd9.E-PWUfNVkpvyNRr--JPLlrdciiTihSdhksmgoehWvE0

{
  "name": "피자에땅",
  "content": "피자에땅 입니다.",
  "address": "서울시 강남구",
  "regionId": "376ddba6-d9ab-4953-aee6-614e1dfeef7e",
  "ownerId": 3
}

### 음식점 삭제
DELETE http://localhost:8080/api/v1/stores/8aa9b4ba-83ae-40c6-9984-760f2c5cbf26
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwNTM3ODg3LCJpYXQiOjE3Mzk5MzMwODd9.E-PWUfNVkpvyNRr--JPLlrdciiTihSdhksmgoehWvE0

### 음식점에 카테고리 생성
POST http://localhost:8080/api/v1/stores/df41f705-a5d4-419c-a372-f9c43c585e07/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzM5OTM1MjQzLCJpYXQiOjE3Mzk5MzE2NDN9.EH1k06aEe9SfHvEYfNk-IWOB8osI6cJutl07gvokFiI

{
  "categoryIdList": [
    "2b5db83c-d0d0-4c66-bbbb-a5e94f053fb7",
    "72f705b4-97ee-4ee3-8c02-78b38b15a5bc"
  ]
}

### 음식점에 카테고리 생성 - 중복 오류
POST http://localhost:8080/api/v1/stores/df41f705-a5d4-419c-a372-f9c43c585e07/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzM5OTM1MjQzLCJpYXQiOjE3Mzk5MzE2NDN9.EH1k06aEe9SfHvEYfNk-IWOB8osI6cJutl07gvokFiI

{
  "categoryIdList": [
    "2b5db83c-d0d0-4c66-bbbb-a5e94f053fb7",
    "2b5db83c-d0d0-4c66-bbbb-a5e94f053fb7",
    "72f705b4-97ee-4ee3-8c02-78b38b15a5bc"
  ]
}