### 유저 생성 (MASTER)
POST {{baseUrl}}/api/v1/users/signup
Content-Type: application/json

{
  "username": "master",
  "password": "!Master123",
  "role": "MASTER"
}

### 유저 로그인 (MASTER)
POST {{baseUrl}}/api/v1/users/login
Content-Type: application/json

{
  "username": "master",
  "password": "!Master123"
}


### 회원 조회
GET {{baseUrl}}/api/v1/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMzg4ODM5LCJpYXQiOjE3NDAzODUyMzl9.K4Vj0TnRQ2yvLcmrI7G76rsNnDUXW46T8R14eN-RA8Q

### 회원 조회(동적쿼리)
GET http://localhost:8080/api/v1/users/search?username=customer&page=0&size=3&sort=createdAt,desc
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMzgzNTE2LCJpYXQiOjE3NDAzNzk5MTZ9.4ZjalK-3LTEScYjwhNK3R5dBDSrYfa_cjOMD-X88kO4


### 회원 정보 수정
PUT {{baseUrl}}/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjdXN0b21lcjgiLCJhdXRoIjoiQ1VTVE9NRVIiLCJleHAiOjE3NDAyMTI1NDMsImlhdCI6MTc0MDIwODk0M30.9GzRoqpaBcM4XApRbXzAoS_O0Rx-n54V74qlGpuYnwY

{
  "username": "updateuzer",
  "password": "Update1234!"
}

### 회원 탈퇴
DELETE {{baseUrl}}/api/v1/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMjExNjQyLCJpYXQiOjE3NDAyMDgwNDJ9.jLgjLfzaX6E7xsPhjbyG_MyANYoYbbkZ4hoNdJdTPgw


### 유저 생성(CUSTOMER)
POST {{baseUrl}}/api/v1/users/signup
Content-Type: application/json

{
  "username": "customer",
  "password": "!Customer123",
  "role": "CUSTOMER"
}

### 유저 로그인 (CUSTOMER)
POST {{baseUrl}}/api/v1/users/login
Content-Type: application/json

{
  "username": "customer",
  "password": "!Customer123"
}

### 유저 생성(OWNER)
POST {{baseUrl}}/api/v1/users/signup
Content-Type: application/json

{
  "username": "owner",
  "password": "!Owner123",
  "role": "OWNER"
}

### 유저 로그인 (OWNER)
GET {{baseUrl}}/api/v1/users/login
Content-Type: application/json

{
  "username": "owner",
  "password": "!Owner123"
}

### 유저 생성(MANAGER)
POST {{baseUrl}}/api/v1/users/signup
Content-Type: application/json

{
  "username": "manager",
  "password": "!Manager123",
  "role": "MANAGER"
}

### 유저 로그인 (MANAGER)
GET {{baseUrl}}/api/v1/users/login
Content-Type: application/json

{
  "username": "manager",
  "password": "!Manager123"
}

