### 유저 생성 (MASTER)
POST http://localhost:8080/api/v1/users/signup
Content-Type: application/json

{
  "username": "master",
  "password": "!Master123",
  "role": "CUSTOMER"
}

### 유저 로그인 (MASTER)
GET http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "username": "master",
  "password": "!Master123"
}

### 회원 조회
GET http://localhost:8080/api/v1/users/1
Content-Type: application/json

### 회원 조회(동적쿼리)
GET http://localhost:8080/api/v1/users/search?page=0&size=3&sort=createdAt,desc
Content-Type: application/json

{
  "role": "CUSTOMER",
  "isDeleted": false
}


### 회원 정보 수정
PUT http://localhost:8080/api/v1/users/1
Content-Type: application/json

{
  "username": "updateUser",
  "password": "update1234",
  "role": "MANAGER"
}

### 회원 탈퇴
DELETE http://localhost:8080/api/v1/users/1
Content-Type: application/json


### 유저 생성(CUSTOMER)
POST http://localhost:8080/api/v1/users/signup
Content-Type: application/json

{
  "username": "customer",
  "password": "!Customer123",
  "role": "CUSTOMER"
}

### 유저 로그인 (CUSTOMER)
GET http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "username": "customer",
  "password": "!Customer123"
}

### 유저 생성(OWNER)
POST http://localhost:8080/api/v1/users/signup
Content-Type: application/json

{
  "username": "owner",
  "password": "!Owner123",
  "role": "OWNER"
}

### 유저 로그인 (OWNER)
GET http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "username": "owner",
  "password": "!Owner123"
}

### 유저 생성(MANAGER)
POST http://localhost:8080/api/v1/users/signup
Content-Type: application/json

{
  "username": "manager",
  "password": "!Manager123",
  "role": "MANAGER"
}

### 유저 로그인 (MANAGER)
GET http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "username": "manager",
  "password": "!Manager123"
}

