### 유저 생성 (MASTER)
POST {{baseUrl}}/api/v1/users/signup
Content-Type: application/json

{
  "username": "master",
  "password": "!Master123",
  "role": "MASTER"
}

### 유저 로그인 (MASTER)
POST {{baseUrl}}/api/v1/users/login
Content-Type: application/json

{
  "username": "master",
  "password": "!Master123"
}


### 회원 조회
GET {{baseUrl}}/api/v1/users/1
Authorization: {{access_token}}

### 회원 조회(동적쿼리)
GET http://localhost:8080/api/v1/users/search?username=customer&page=0&size=3&sort=createdAt,desc
Authorization: {{access_token}}


### 회원 정보 수정
PUT {{baseUrl}}/api/v1/users
Content-Type: application/json
Authorization: {{access_token}}

{
  "username": "updateuzer",
  "password": "Update1234!"
}

### 회원 탈퇴
DELETE {{baseUrl}}/api/v1/users/1
Content-Type: application/json
Authorization: {{access_token}}


### 유저 생성(CUSTOMER)
POST {{baseUrl}}/api/v1/users/signup
Content-Type: application/json

{
  "username": "customer",
  "password": "!Customer123",
  "role": "CUSTOMER"
}

### 유저 로그인 (CUSTOMER)
POST {{baseUrl}}/api/v1/users/login
Content-Type: application/json

{
  "username": "customer",
  "password": "!Customer123"
}

### 유저 생성(OWNER)
POST {{baseUrl}}/api/v1/users/signup
Content-Type: application/json

{
  "username": "owner",
  "password": "!Owner123",
  "role": "OWNER"
}

### 유저 로그인 (OWNER)
POST {{baseUrl}}/api/v1/users/login
Content-Type: application/json

{
  "username": "owner",
  "password": "!Owner123"
}

### 유저 생성(MANAGER)
POST {{baseUrl}}/api/v1/users/signup
Content-Type: application/json

{
  "username": "manager",
  "password": "!Manager123",
  "role": "MANAGER"
}

### 유저 로그인 (MANAGER)
POST {{baseUrl}}/api/v1/users/login
Content-Type: application/json

{
  "username": "manager",
  "password": "!Manager123"
}

