spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        spring.jpa.open-in-view: false
        format_sql: true
        default_batch_fetch_size: 10
jwt:
  secret_key: ${JWT_SECRET_KEY}
openai:
  model: ${OPENAI_MODEL}
  api:
    url: ${OPENAI_API_URL}
    key: ${OPENAI_API_KEY}
