spring:
  config:
    import: optional:file:.env.test[.properties]
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/ecommerce
    username: admin
    password:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        spring.jpa.open-in-view: false
        format_sql: true
        default_batch_fetch_size: 10