### 회원 가입
POST http://localhost:8080/api/v1/users/signup
Content-Type: application/json

{
  "username": "master",
  "password": "!Master123",
  "role": "CUSTOMER"
}

### 로그인
GET http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "username": "master",
  "password": "!Master123"
}

### 지역 생성
POST http://localhost:8080/api/v1/regions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMTMyOTE0LCJpYXQiOjE3NDAxMjkzMTR9.Y-8F8ElzKmnNuZw8PCZveU_v7cLcbghCv7DS3JFtMUg

{
  "regionName": "서울시"
}

### 카테고리 생성
POST http://localhost:8080/api/v1/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzM5ODU5NjQ5LCJpYXQiOjE3Mzk4NTYwNDl9.VC0YwrVoNFo_9VMyovczvf1YBC82gIgQ4_m6QlsohCQ

{
  "name": "야식",
  "patentId": null
}