### 회원 가입
POST {{baseUrl}}/api/v1/users/signup
Content-Type: application/json

{
  "username": "{{master_id}}",
  "password": "{{master_pw}}",
  "role": "{{master_role}}"
}

### 로그인
POST {{baseUrl}}/api/v1/users/login
Content-Type: application/json

{
  "username": "{{master_id}}",
  "password": "{{master_pw}}"
}
> {%
  client.global.set("access_token", response.headers.valueOf("Authorization"))
%}


### 지역 생성
POST {{baseUrl}}/api/v1/regions
Content-Type: application/json
Authorization: {{access_token}}

{
  "regionName": "서울시"
}
> {%
  client.global.set("regionId", response.body.result.regionId)
%}
