### 회원 가입
POST {{baseUrl}}/api/v1/users/signup
Content-Type: application/json

{
  "username": "{{customer_id}}",
  "password": "{{customer_pw}}",
  "role": "{{customer_role}}"
}

### 로그인
POST {{baseUrl}}/api/v1/users/login
Content-Type: application/json

{
  "username": "{{customer_id}}",
  "password": "{{customer_pw}}"
}
> {%
  client.global.set("access_token", response.headers.valueOf("Authorization"))
%}

### 주소 생성
POST {{baseUrl}}/api/v1/addresses
Content-Type: application/json
Authorization: {{access_token}}

{
  "addressName": "seoul",
  "regionId": "{{regionId}}"
}

### 음식점 조회(주소 기반)
GET {{baseUrl}}/api/v1/stores/search
    ?searchText=상점
    &categoryNameSearchText=야식
    &storeNameSearchText=상점
    &storeSearchAddress=서울
    &regionId={{regionId}}
    &ownerId=2
    &categoryId={{categoryId}}
    &sort=name,desc,created_at
    &size=10
    &page=1
Authorization: {{access_token}}

### 주문 생성
POST {{baseUrl}}/api/v1/orders
Content-Type: application/json
Authorization: {{access_token}}

{
  "orderProducts": [
    {
      "productId": "{{productId}}",
      "price": 10000.00,
      "quantity": 1
    }
  ],
  "orderType": "DELIVERY",
  "paymentType": "CARD"
}

### 주문 내역 조회
GET {{baseUrl}}/api/v1/orders/search?orderStatus=ORDER_COMPLETED&page=0&size=10&sort=createdAt,asc
Content-Type: application/json
Authorization: {{access_token}}
