### 회원 가입
POST {{baseUrl}}/api/v1/users/signup
Content-Type: application/json

{
  "username": "customer",
  "password": "!Customer123",
  "role": "CUSTOMER"
}

### 로그인
GET {{baseUrl}}/api/v1/users/login
Content-Type: application/json

{
  "username": "customer",
  "password": "!Customer123"
}

### 주소 생성
POST {{baseUrl}}/api/v1/addresses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMTMxNTA4LCJpYXQiOjE3NDAxMjc5MDh9.8rkrN69uV-Tt3bBF7nKe8V0kcHq3zYtAroXSJuu8Ikg

{
  "addressName": "seoul",
  "regionId": "6ebdc634-bb2a-4651-b0de-01a9d7bd07e5"
}

### 음식점 조회(주소 기반)
GET {{baseUrl}}/api/v1/stores/search
    ?searchText=상점
    &categoryNameSearchText=야식
    &storeNameSearchText=상점
    &storeSearchAddress=서울
    &regionId=376ddba6-d9ab-4953-aee6-614e1dfeef7e
    &ownerId=2
    &categoryId=72f705b4-97ee-4ee3-8c02-78b38b15a5bc
    &sort=name,desc,created_at
    &size=10
    &page=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwNTM3ODg3LCJpYXQiOjE3Mzk5MzMwODd9.E-PWUfNVkpvyNRr--JPLlrdciiTihSdhksmgoehWvE0

### 주문 생성
POST {{baseUrl}}/api/v1/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMDE3NzEzLCJpYXQiOjE3NDAwMTQxMTN9.WycI2pW5Lh7cAqOL97UYntFeXiADhv1GqsD1bXVQ4eU

{
  "orderProducts": [
    {
      "productId": "26c7366c-2560-48a6-93fd-37aa8c19e0f3",
      "price": 10000.00,
      "quantity": 1
    },
    {
      "productId": "13c0a47a-3d34-4dfe-bf0b-babb6e12af82",
      "price": 10000.00,
      "quantity": 2
    }
  ],
  "orderType": "DELIVERY",
  "paymentType": "CARD"
}

### 주문 내역 조회
GET {{baseUrl}}/api/v1/orders/search?orderStatus=ORDER_COMPLETED&page=0&size=10&sort=createdAt,asc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjdXN0b21lciIsImF1dGgiOiJDVVNUT01FUiIsImV4cCI6MTc0MDMwMDg2MiwiaWF0IjoxNzQwMjk3MjYyfQ.IM7s9tkdOpTEPNmcRjJE2DUd0JE6W3NKeb_AG4snTqw

### 주문 삭제 (5분 이내)
PUT {{baseUrl}}/api/v1/orders/c6c331bb-58df-4f0f-9b05-864c98c0e630/cancel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjdXN0b21lciIsImF1dGgiOiJDVVNUT01FUiIsImV4cCI6MTc0MDQwOTU0MSwiaWF0IjoxNzQwNDA1OTQxfQ.7mEagoGZe2V3xcLq0FWFOK2JcPFqpWVF96iI-6SNr9M