### 회원 가입
POST {{baseUrl}}/api/v1/users/signup
Content-Type: application/json

{
  "username": "owner",
  "password": "!Owner123",
  "role": "OWNER"
}


### 로그인
POST {{baseUrl}}/api/v1/users/login
Content-Type: application/json

{
  "username": "owner",
  "password": "!Owner123"
}

> {%
  client.global.set("access_token", response.headers.valueOf("Authorization"))
%}

### 주소 생성
POST {{baseUrl}}/api/v1/addresses
Content-Type: application/json
Authorization: {{access_token}}

{
  "addressName": "seoul",
  "regionId": "d285b0ff-1568-47f0-84e4-e09ebe7f7404"
}

### 음식점 생성
POST {{baseUrl}}/api/v1/stores
Content-Type: application/json
Authorization: {{access_token}}

{
  "name": "상점1",
  "content": "상점1 입니다.",
  "address": "seoul",
  "regionId": "6ebdc634-bb2a-4651-b0de-01a9d7bd07e5",
  "ownerId": "2"
}

### 상품 생성
POST {{baseUrl}}/api/v1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwNTM3ODg3LCJpYXQiOjE3Mzk5MzMwODd9.E-PWUfNVkpvyNRr--JPLlrdciiTihSdhksmgoehWvE0


{
  "name": "상점1-상품01",
  "price": 50000,
  "isDisplay": false,
  "storeId": "d2a88144-242d-4a87-b607-4846a66d89de"
}

### 음식점 조회 {storeId}
GET {{baseUrl}}/api/v1/stores/d2a88144-242d-4a87-b607-4846a66d89de
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwNTM3ODg3LCJpYXQiOjE3Mzk5MzMwODd9.E-PWUfNVkpvyNRr--JPLlrdciiTihSdhksmgoehWvE0

### 메뉴 수정 {productId}
PUT {{baseUrl}}/api/v1/products/ea451ea9-aba1-4abc-a6d9-4bba27a48a78
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwNTM3ODg3LCJpYXQiOjE3Mzk5MzMwODd9.E-PWUfNVkpvyNRr--JPLlrdciiTihSdhksmgoehWvE0

{
  "name": "고바",
  "price": 25000,
  "isDisplay": true
}

### 주문 수정(관리자가 주문 취소)
PUT {{baseUrl}}/api/v1/orders/b7745ace-f7c5-4eeb-a84f-203d533d21c0/status?status=ORDER_CANCELED
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvd25lciIsImF1dGgiOiJPV05FUiIsImV4cCI6MTc0MDM3MzQ3NiwiaWF0IjoxNzQwMzY5ODc2fQ.eC0Ux31DJdlqpP1m3cJAzxtZnw0z7jn1VgYyyy7m7lI



### 주문 수정(관리자가 주문 접수)
PUT {{baseUrl}}/api/v1/orders/b7745ace-f7c5-4eeb-a84f-203d533d21c0/status?status=ORDER_COMPLETED
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvd25lciIsImF1dGgiOiJPV05FUiIsImV4cCI6MTc0MDM3MzUzNiwiaWF0IjoxNzQwMzY5OTM2fQ.a61vupZxPPDOr49UmE7BJIvYgDvYhHMRa-nZC5lFs7s