### 회원 가입
POST {{baseUrl}}/api/v1/users/signup
Content-Type: application/json

{
  "username": "{{owner_id}}",
  "password": "{{owner_pw}}",
  "role": "{{owner_role}}"
}


### 로그인
POST {{baseUrl}}/api/v1/users/login
Content-Type: application/json

{
  "username": "{{owner_id}}",
  "password": "{{owner_pw}}"
}

> {%
  client.global.set("access_token", response.headers.valueOf("Authorization"))
%}

### 주소 생성
POST {{baseUrl}}/api/v1/addresses
Content-Type: application/json
Authorization: {{access_token}}

{
  "addressName": "seoul",
  "regionId": "{{regionId}}"
}

### 음식점 생성
POST {{baseUrl}}/api/v1/stores
Content-Type: application/json
Authorization: {{access_token}}

{
  "name": "상점1",
  "content": "상점1 입니다.",
  "address": "seoul",
  "regionId": "{{regionId}}",
  "ownerId": "2"
}
> {%
  client.global.set("location", response.headers.valueOf("Location"))
  client.log("get location ->> " + client.global.get("location"))
%}


### 음식점 조회 {storeId}
GET {{baseUrl}}/{{location}}
Content-Type: application/json
Authorization: {{access_token}}

> {%
  client.global.set("storeId", response.body.id)
  client.log("get storeId ->> " + client.global.get("storeId"))
%}

### 상품 생성
POST {{baseUrl}}/api/v1/products
Content-Type: application/json
Authorization: {{access_token}}


{
  "name": "상점1-상품01",
  "price": 50000,
  "isDisplay": false,
  "storeId": "{{storeId}}"
}
> {%
  client.global.set("productId", response.headers.valueOf("productId"))
%}

### 메뉴 수정 {productId}
PUT {{baseUrl}}/api/v1/products/{{productId}}
Content-Type: application/json
Authorization: {{access_token}}

{
  "name": "고바",
  "price": 25000,
  "isDisplay": true
}
