### 회원 가입
POST http://localhost:8080/api/v1/users/signup
Content-Type: application/json

{
  "username": "owner",
  "password": "!Owner123",
  "role": "OWNER"
}

### 로그인
GET http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "username": "owner",
  "password": "!Owner123"
}

### 음식점 생성
POST http://localhost:8080/api/v1/stores
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwNTM3ODg3LCJpYXQiOjE3Mzk5MzMwODd9.E-PWUfNVkpvyNRr--JPLlrdciiTihSdhksmgoehWvE0

{
  "name": "상점1",
  "content": "상점1 입니다.",
  "address": "seoul",
  "regionId": "6ebdc634-bb2a-4651-b0de-01a9d7bd07e5",
  "ownerId": "2"
}

### 상품 생성
POST http://localhost:8080/api/v1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwNTM3ODg3LCJpYXQiOjE3Mzk5MzMwODd9.E-PWUfNVkpvyNRr--JPLlrdciiTihSdhksmgoehWvE0


{
  "name": "상점1-상품01",
  "price": 50000,
  "isDisplay": false,
  "storeId": "d2a88144-242d-4a87-b607-4846a66d89de"
}

### 음식점 조회 {storeId}
GET http://localhost:8080/api/v1/stores/d2a88144-242d-4a87-b607-4846a66d89de
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwNTM3ODg3LCJpYXQiOjE3Mzk5MzMwODd9.E-PWUfNVkpvyNRr--JPLlrdciiTihSdhksmgoehWvE0

### 메뉴 수정 {productId}
PUT http://localhost:8080/api/v1/products/ea451ea9-aba1-4abc-a6d9-4bba27a48a78
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXIiLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwNTM3ODg3LCJpYXQiOjE3Mzk5MzMwODd9.E-PWUfNVkpvyNRr--JPLlrdciiTihSdhksmgoehWvE0

{
  "name": "고바",
  "price": 25000,
  "isDisplay": true
}

### 주문 처리
